apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-master
  labels:
    app: spark
    unit: master
data:
  HADOOP_DAEMONS: |
    namenode
    resourcemanager
    secondarynamenode
  SPARK_DAEMONS: |
    livy
  YARN_SCHEDULER_MINIMUM_ALLOCATION_MB: "128"
  YARN_SCHEDULER_MAXIMUM_ALLOCATION_MB: "12288"
  YARN_SCHEDULER_MINIMUM_ALLOCATION_VCORES: "1"
  YARN_SCHEDULER_MAXIMUM_ALLOCATION_VCORES: "12"