# Written by Mutlu Polatcan
# 12.01.2020
apiVersion: v1
kind: Service
metadata:
  name: hdfs-slave-webapps
spec:
  selector:
    app: spark
    unit: hdfs-slave
  ports:
    - port: 9864 # Datanode HTTP Port
      name: dn-http-port
    - port: 9865 # Datanode HTTPS Port
      name: dn-https-port
  type: NodePort