# Written by Mutlu Polatcan
# 12.01.2020
apiVersion: v1
kind: Service
metadata:
  name: spark-worker-webapps
spec:
  selector:
    app: spark
    unit: spark-worker
  ports:
    - port: 8042 # YARN Nodemanager HTTP Port
      name: nm-http-port
    - port: 8044 # YARN Nodemanager HTTPS Port
      name: nm-https-port
  type: NodePort