base_dockerfile_template: |
  ARG JAVA_VERSION=""
  ARG HADOOP_VERSION=""

  FROM mpolatcan/hadoop:${{HADOOP_VERSION}}-java${{JAVA_VERSION}}

  MAINTAINER Mutlu Polatcan <mutlupolatcan@gmail.com>

  ARG LIVY_VERSION=""
  ARG LIVY_ZIP_FOLDER_NAME="apache-livy-${{LIVY_VERSION}}-incubating-bin"
  ARG LIVY_DOWNLOAD_LINK="https://www-eu.apache.org/dist/incubator/livy/${{LIVY_VERSION}}-incubating/${{LIVY_ZIP_FOLDER_NAME}}.zip"

  ENV SPARK_HOME="${{HDUSER_HOME}}/spark" \
      LIVY_HOME="${{HDUSER_HOME}}/livy"
  ENV SPARK_CONF_DIR="${{SPARK_HOME}}/conf" \
      LIVY_CONF_DIR="${{LIVY_HOME}}/conf" \
      SPARK_SERVICES="NULL" \
      PATH=$PATH:$SPARK_HOME/bin:$SPARK_HOME/sbin:$LIVY_HOME/bin \
  {env_vars}

  ADD entrypoint.sh ${{HDUSER_HOME}}/spark_entrypoint.sh
  ADD config_loader.sh ${{HDUSER_HOME}}/spark_config_loader.sh

  USER root
  RUN mkdir -p ${{SPARK_HOME}} ${{LIVY_HOME}} && \
      chmod +x spark_config_loader.sh spark_entrypoint.sh && \
      wget ${{LIVY_DOWNLOAD_LINK}} && \
      unzip ${{LIVY_ZIP_FOLDER_NAME}}.zip && \
      mv ${{LIVY_ZIP_FOLDER_NAME}}/* ${{LIVY_HOME}} && \
      rm -r ${{LIVY_ZIP_FOLDER_NAME}} ${{LIVY_ZIP_FOLDER_NAME}}.zip && \
      chown -R hduser:hadoop ${{LIVY_HOME}}

config_loader_sh_template: |
  #!/usr/bin/env bash
  function load_config() {{
    if [[ "$2" != "NULL" && "$4" == "spark" ]]; then
        printf "$1\t$2\n" >> "${{SPARK_CONF_DIR}}/$3"
    elif [[ "$2" != "NULL" && "$4" == "livy" ]]; then
        printf "$1 = $2\n" >> "${{LIVY_CONF_DIR}}/$3"
    fi
  }}

  {load_fn_calls}

config_files:
  - path: spark_configs/spark-defaults.yaml
    filename: spark-defaults.conf
    config_type: spark
  - path: spark_configs/livy-defaults.yaml
    filename: livy.conf
    config_type: livy

output_dir: ../../base