apiVersion: v1
kind: Service
metadata:
  name: hdfs-master-webapps
spec:
  selector:
    app: spark
    unit: hdfs-master
  ports:
    - port: 9870 # Namenode HTTP Port
      name: nn-http-port
    - port: 9871 # Namenode HTTPS Port
      name: nn-https-port
  type: NodePort