apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: hdfs-slave
  labels:
    app: spark
    unit: hdfs-slave
spec:
  replicas: 1
  serviceName: spark
  selector:
    matchLabels:
      app: spark
      unit: hdfs-slave
  template:
    metadata:
      name: hdfs-slave
      labels:
        app: spark
        unit: hdfs-slave
    spec:
      restartPolicy: Always
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: kubernetes.io/hostname
              labelSelector:
                matchExpressions:
                  - key: unit
                    operator: In
                    values:
                      - hdfs-slave
                      - hdfs-master
      initContainers:
        - name: hdfs-slave-init
          image: mpolatcan/pyspark:2.3.4-hadoop-3.2.1-java8
          imagePullPolicy: Always
          command:
            - /bin/bash
          args:
            - -c
            - $(INIT_SCRIPT)
          envFrom:
            - configMapRef:
                name: spark-init
          volumeMounts:
            - mountPath: /spark-state
              name: hdfs-slave-volume
      containers:
        - name: hdfs-slave
          image: mpolatcan/pyspark:2.3.4-hadoop-3.2.1-java8
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: hdfs-slave
          volumeMounts:
            - mountPath: /home/hduser
              name: hdfs-slave-volume
          ports:
            - containerPort: 9864
          livenessProbe:
            tcpSocket:
              port: 9864
            initialDelaySeconds: 15
            periodSeconds: 2
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 9864
            initialDelaySeconds: 15
            periodSeconds: 2
            failureThreshold: 3
      securityContext:
        fsGroup: 1000
  volumeClaimTemplates:
    - metadata:
        name: hdfs-slave-volume
      spec:
        storageClassName: gce-pd-hdd
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi