# Written by Mutlu Polatcan
# 22.11.2019
version: "3.5"
services:
  master:
    image: mpolatcan/spark:2.3.4-hadoop-3.3.0-java8
    container_name: master
    hostname: master
    environment:
      HADOOP_DAEMONS: |
        namenode
        resourcemanager
        secondarynamenode
      SPARK_SERVICES: |
        livy
      FS_DEFAULTFS: "hdfs://0.0.0.0:9000"
      YARN_SCHEDULER_MINIMUM_ALLOCATION_MB: "128"
      YARN_SCHEDULER_MAXIMUM_ALLOCATION_MB: "1536"
      YARN_NODEMANAGER_VMEM_CHECK_ENABLED: "false"
      YARN_NODEMANAGER_RESOURCE_MEMORY_MB: "1536"
      YARN_NODEMANAGER_RESOURCE_CPU_VCORES: "2"
    ports:
      - 8088:8088 # resource manager port
      - 9868:9868 # secondary namenode port
      - 9864:9864 # datanode port
      - 9870:9870 # namenode port
      - 8480:8480 # journalnode port
      - 8998:8998 # livy port

  worker:
    image: mpolatcan/spark:2.3.4-hadoop-3.3.0-java8
    environment:
      HADOOP_DAEMONS: |
        datanode
        nodemanager
      FS_DEFAULTFS: "hdfs://master:9000"
      YARN_RESOURCEMANAGER_HOSTNAME: "master"
      YARN_NODEMANAGER_RESOURCE_MEMORY_MB: "1536"
      YARN_NODEMANAGER_RESOURCE_CPU_VCORES: "2"
    links:
      - master