version: "3"
services:
  spark-master:
    image: mpolatcan/spark:2.3.4-hadoop-3.2.1-java8
    container_name: resourcemanager
    hostname: resourcemanager
    environment:
      HADOOP_DAEMONS: |
          resourcemanager
      SPARK_SERVICES: |
          livy
      DFS_NAMENODE_HOSTNAME: "namenode"
      YARN_SCHEDULER_MINIMUM_ALLOCATION_MB: "128"
      YARN_SCHEDULER_MAXIMUM_ALLOCATION_MB: "1536"
    ports:
      - 8088:8088

  spark-worker:
    image: mpolatcan/spark:2.3.4-hadoop-3.2.1-java8
    environment:
      HADOOP_DAEMONS: |
          nodemanager
      DFS_NAMENODE_HOSTNAME: "namenode"
      YARN_RESOURCEMANAGER_HOSTNAME: "resourcemanager"
      YARN_NODEMANAGER_RESOURCE_MEMORY_MB: "1536"
      YARN_NODEMANAGER_RESOURCE_CPU_VCORES: "2"
    ports:
      - 8042
      - 8

  hdfs-master:
    image: mpolatcan/spark:2.3.4-hadoop-3.2.1-java8
    container_name: namenode
    hostname: namenode
    environment:
      HADOOP_DAEMONS: |
          namenode
    ports:
      - 9870:9870

  hdfs-slave:
    image: mpolatcan/spark:2.3.4-hadoop-3.2.1-java8
    environment:
      HADOOP_DAEMONS: |
          datanode
      DFS_NAMENODE_HOSTNAME: "namenode"
    ports:
      - 9864